name: Lint Commit Messages
on: push

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: "[KDR-[0-9]+[0-9]+[0-9]][A-Z]+.*"
          error: "Ваш коммит должен быть формата '[KDR-000] Commit message with capital letter'."
